name: Django                                  # workflow name

on:
  push:
    branches:                                 # similar to "only" in GitLab
      - main

jobs:
  build:
    runs-on: ubuntu-22.04                    # similar to "image" in GitLab
    steps:
      - run: echo "This is a build step"      # similar to "script" in GitLab

  test:
    runs-on: ubuntu-22.04
    steps:
      - run: echo "This is a test step"

  oast:
    runs-on: ubuntu-22.04
    needs: test
    steps:
      - uses: actions/checkout@v2
      - run: docker run --rm -v $(pwd):/src hysnsec/safety check -r requirements.txt --json > oast-results.json
      - uses: actions/upload-artifact@v4
        with:
          name: Safety
          path: oast-results.json
        if: always()                        # what is this for?

  integration:
    runs-on: ubuntu-22.04
    steps:
      - run: echo "This is an integration step"
      - run: exit 1

  prod:
    runs-on: ubuntu-22.04
    steps:
      - run: echo "This is a deploy step"
